/* Mesh.h
 * Author : Kozhukharov Nikita
 * Mesh class is used to draw connected object, generated by one array of vertices
 */

#pragma once

//#include <../Renderer/Shaders.h>
//#include <../Math/Vec.h>

#include <Renderer/Shaders.h>
#include <Math/Vec.h>
#include <vector>
#include <string>


struct Vertex {
    vec3 Position;
    vec3 Normal;
    vec2 TexCoords;
    Vertex(vec3 p, vec3 n, vec2 t);
};

struct Texture {
    unsigned int id;
    std::string type;
};


class Mesh {
    unsigned int VAO, VBO, EBO;
    void setupMesh();

    std::vector<Vertex>       vertices;
    std::vector<unsigned int> indices;
    std::vector<Texture>      textures;

public:
    // vectors will be moved to avoid copying
    Mesh(std::vector<Vertex> & vertices, std::vector<unsigned int> & indices,
        std::vector<Texture> & textures);
    // shader is necessary to give him texture attributes
    void draw(const ShaderProgram & shader);            

    ~Mesh();
};
